name: Trigger Home Env

on:
  push:
    branches:
      - master

jobs:
  # this is needed to wait for the new docker image to be build and published to the registry
  # so that we can use the image to run ui of the needed commit related version as part of local-env
  # the idea is taken from here https://stackoverflow.com/a/71489231
  build:
    uses: ./.github/workflows/docker-build-and-push.yml
    # without this it cannot login to the registry
    secrets: inherit

  trigger_home_env:
    needs: build
    uses: Yam1xTest/home-github-workflows/.github/workflows/sync-env.yml@feature/add_sync_workflow
    with:
      # pelican-env is used to define which env will be synced
      target-env: home-env
      # path-to-values is used to define where the values files is stored
      path-to-values: deploy/values-env-synchronizer.yaml.gotmpl
      # path-to-helmfile is used to define where the helmfile is stored
      path-to-helmfile: deploy/helmfile.yaml
    secrets: inherit
